/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/user/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the user's account defaults + non-secret server overrides
         * @description Returns the merged user-settings document. The server reads
         *     `server/user-settings.json` (created on first GET with defaults) and
         *     layers in env-derived read-only fields: `apiKeyStatus`,
         *     `workspaceRoot`, `workspaceSource`. The Gemini API key itself is
         *     never echoed back — only the binary "is something set in .env" flag.
         */
        get: operations["getUserSettings"];
        /**
         * Update the user's account defaults + non-secret server overrides
         * @description Partial update. Only the writable fields from the request body are
         *     persisted; `apiKeyStatus`, `workspaceRoot`, `workspaceSource` are
         *     derived and silently ignored if submitted. Any field named
         *     `geminiApiKey` (or similar secret-shaped key) is also dropped — the
         *     API key never leaves `server/.env`. Changes to `sidecarUrl` take
         *     effect on the next request; `workspaceDirOverride` is persisted
         *     but requires a server restart to apply.
         */
        put: operations["putUserSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated change log across every book in the workspace
         * @description Fans out `.audiobook/change-log.json` from every book in the workspace,
         *     attaches `bookId`, `bookTitle`, and `author` to each event, and returns
         *     the flattened list sorted newest-first. Books without an on-disk
         *     change-log are skipped. Backs the global Change Log view.
         */
        get: operations["getWorkspaceChangelog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List books in the on-disk workspace
         * @description Walks the workspace `books/<Author>/<Series>/<Book>/` tree and returns
         *     the grouped library used by the frontend's book-library view. Status
         *     per book is derived from the presence of `.audiobook/state.json`,
         *     `cast.json`, and the audio output count.
         */
        get: operations["getLibrary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a manuscript and stage it for confirmation
         * @description Parse-only: returns the parsed text plus best-effort author/series/title
         *     metadata, and stashes the result in memory under a short tempId. Nothing
         *     is written to disk. The frontend then renders a confirm-metadata form;
         *     on submit, POST /api/books drains the staging entry into the workspace.
         */
        post: operations["importManuscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm metadata and write a book into the workspace
         * @description Drains the staged import identified by `tempId`, writes
         *     `manuscript.<ext>` and `.audiobook/state.json` into
         *     `books/<Author>/<Series>/<Title>/`, and returns the resulting bookId +
         *     manuscriptId. Returns 409 with a `suggestedTitle` if a book with the
         *     same slug already exists.
         */
        post: operations["confirmBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manuscripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a manuscript */
        post: operations["uploadManuscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manuscripts/{manuscriptId}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run cast + chapter analysis
         * @description Streams phase progress over Server-Sent Events while the analysis
         *     runs. The final SSE event carries the full `AnalyseResponse`.
         */
        post: operations["analyseManuscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/{voiceId}/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synthesise a ~12-second voice preview
         * @description Renders a short sample of the voice via the configured TTS provider
         *     (free-tier Gemini). The server caches the WAV on disk keyed by
         *     `voiceId` + `modelKey`; subsequent requests with the same key return
         *     immediately with `cached: true`. The frontend plays the URL with a
         *     plain `<audio>` element.
         */
        post: operations["getVoiceSample"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/voice-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match characters to existing library voices */
        post: operations["matchVoices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/generation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate chapter audio with progress streaming
         * @description Single long-running POST that streams generation progress as SSE
         *     events. Mirrors the analysis route shape (`POST /api/manuscripts/{id}/
         *     analysis`). Each `data: <json>` payload follows the GenerationTick
         *     schema. Synthesises chapters one at a time; per-chapter completion
         *     writes `audio/<chapterSlug>.mp3` + `audio/<chapterSlug>.segments.json`
         *     into the workspace book directory. Legacy `.wav` files from chapters
         *     generated before the MP3 switch keep playing — the locator probes
         *     `.mp3` first, falls back to `.wav` (see plan 28).
         */
        post: operations["streamGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/chapters/{chapterId}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a chapter's playable audio + waveform metadata */
        get: operations["getChapterAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List voices derived from every confirmed cast in the workspace
         * @description Walks `books/<Author>/<Series>/<Book>/.audiobook/cast.json` for every
         *     book where `state.castConfirmed === true` and aggregates the characters
         *     into a deduplicated voice library. There is no separate voice store —
         *     a "voice" is the reusable identity of a previously-cast character. The
         *     `id` matches what the TTS layer hashes for prebuilt-voice picking, so
         *     cached samples at `/audio/voices/{id}-{modelKey}-{paramHash}.mp3`
         *     line up. The trailing hash captures the synthesis inputs so attribute
         *     edits in the profile drawer correctly bust the cache.
         */
        get: operations["getVoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/{voiceId}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Pin or unpin a voice in the workspace library
         * @description Toggles a workspace-level pin flag persisted to
         *     `audiobook-workspace/voices.json`. Pinned voices sort to the top of
         *     the library response so favourites stay at hand across books.
         */
        put: operations["setVoicePin"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pending A/B revisions + voice-drift events
         * @description Polled every 30 s by the client, or pushed via the generation stream.
         */
        get: operations["pollRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserSettings: {
            /**
             * @description Free-text name shown in the top-bar avatar and used as the
             *     author of editorial actions in the change log. Seeded to a
             *     placeholder on first run; user can edit any time.
             */
            displayName: string;
            /**
             * @description Analysis model id from src/lib/models.ts MODEL_OPTIONS. Used as
             *     the initial value of ui.selectedModel when a book has no
             *     persisted analysis-model choice (seed-only; per-book picks win
             *     after).
             */
            defaultAnalysisModel: string;
            /**
             * @description Frontend engine group from src/lib/tts-models.ts (TtsEngineId).
             *     Used to filter the model dropdown's initial state.
             * @enum {string}
             */
            defaultTtsEngine: "local" | "gemini";
            /**
             * @description TTS model key from src/lib/tts-models.ts. Used as the initial
             *     value of ui.ttsModelKey when a book has no persisted TTS-model
             *     choice (seed-only).
             * @enum {string}
             */
            defaultTtsModelKey: "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
            /**
             * @description Overrides the LOCAL_TTS_URL env var. Re-read on every request
             *     by the sidecar provider + health probe.
             */
            sidecarUrl: string;
            /**
             * @description Optional override for the WORKSPACE_DIR env var. Read once at
             *     server startup — changes require a server restart to apply
             *     (UI flags this with a "restart required" badge).
             */
            workspaceDirOverride?: string | null;
            /**
             * @description Whether process.env.GEMINI_API_KEY is non-empty. The key value
             *     itself is never returned over the wire — the UI uses this flag
             *     to render a "set in server/.env" pill.
             * @enum {string}
             */
            readonly apiKeyStatus: "set" | "unset";
            /** @description Resolved absolute path of the active workspace root. */
            readonly workspaceRoot: string;
            /**
             * @description Where WORKSPACE_ROOT was resolved from. `override` when
             *     user-settings.json's workspaceDirOverride was used at boot,
             *     `env` when WORKSPACE_DIR was, `default` when the built-in
             *     `../audiobook-workspace` fallback applied.
             * @enum {string}
             */
            readonly workspaceSource: "env" | "default" | "override";
        };
        /**
         * @description Partial update payload. Read-only fields (apiKeyStatus,
         *     workspaceRoot, workspaceSource) are ignored. Any `geminiApiKey`-
         *     shaped field is dropped — the API key only lives in server/.env.
         */
        UserSettingsPatch: {
            displayName?: string;
            defaultAnalysisModel?: string;
            /** @enum {string} */
            defaultTtsEngine?: "local" | "gemini";
            /** @enum {string} */
            defaultTtsModelKey?: "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
            sidecarUrl?: string;
            workspaceDirOverride?: string | null;
        };
        LibraryResponse: {
            authors: components["schemas"]["LibraryAuthor"][];
        };
        LibraryAuthor: {
            name: string;
            series: components["schemas"]["LibrarySeries"][];
        };
        LibrarySeries: {
            name: string;
            books: components["schemas"]["LibraryBook"][];
        };
        LibraryBook: {
            /** @description slug(author)__slug(series)__slug(title) */
            bookId: string;
            title: string;
            author: string;
            series: string;
            /** @description Series position. Allows decimals for novellas (e.g. 1.5). */
            seriesPosition?: number | null;
            isStandalone: boolean;
            /** @enum {string} */
            status: "not_analysed" | "analysing" | "cast_pending" | "generating" | "complete" | "unreadable" | "orphaned";
            manuscriptId?: string;
            chapterCount: number;
            completedChapters: number;
            characterCount: number;
            voiceCount: number;
            matchedFromLibrary?: number;
            progress?: number;
            /** @description human-formatted total runtime, e.g. '4h 38m' */
            runtime?: string;
            /** @description human-formatted relative time, e.g. '2 min ago' */
            lastWorkedOn: string;
            coverGradient: string[];
            pinned?: boolean;
        };
        ImportCandidate: {
            /** @enum {string} */
            format: "markdown" | "plaintext" | "epub" | "pdf";
            title: string;
            author?: string | null;
            series?: string | null;
            /** @description Series position. Allows decimals for novellas (e.g. 1.5). */
            seriesPosition?: number | null;
            sourceText: string;
            wordCount: number;
            byteSize: number;
            chapters: {
                id: number;
                title: string;
            }[];
        };
        ImportResponse: {
            /** @example imp_abc123 */
            tempId: string;
            candidate: components["schemas"]["ImportCandidate"];
        };
        ConfirmBookRequest: {
            tempId: string;
            author: string;
            series?: string;
            /** @description Series position. Allows decimals for novellas (e.g. 1.5). */
            seriesPosition?: number | null;
            title: string;
            isStandalone: boolean;
        };
        ConfirmBookResponse: components["schemas"]["UploadResponse"] & {
            bookId: string;
            author: string;
            series: string;
            /** @description Series position. Allows decimals for novellas (e.g. 1.5). */
            seriesPosition?: number | null;
            isStandalone: boolean;
            paths: {
                bookDir: string;
                manuscript: string;
                dotAudiobook: string;
            };
        };
        UploadResponse: {
            /** @example mns_abc123 */
            manuscriptId: string;
            /** @enum {string} */
            format: "markdown" | "plaintext" | "epub" | "pdf";
            title: string;
            wordCount: number;
            byteSize: number;
            /** Format: date-time */
            uploadedAt: string;
            /** @description Normalised plain-text body. */
            sourceText: string;
        };
        AnalysePhaseEvent: {
            phaseId: number;
            progress: number;
            label?: string;
        };
        AnalyseResponse: {
            /** @example ns */
            bookId: string;
            manuscriptId: string;
            title: string;
            phaseTimings: {
                id?: number;
                label?: string;
                /** @description milliseconds */
                duration?: number;
            }[];
            characters: components["schemas"]["Character"][];
            chapters: components["schemas"]["Chapter"][];
            sentences: components["schemas"]["Sentence"][];
            /** @description Hints from a pre-pass against the user's voice library. */
            libraryMatches?: {
                characterId?: string;
                voiceId?: string;
                confidence?: number;
            }[];
        };
        CharacterMatchInput: {
            id: string;
            attributes: string[];
            tone?: {
                warmth?: number;
                pace?: number;
                authority?: number;
                emotion?: number;
            };
            evidenceQuotes?: string[];
        };
        VoiceMatchResponse: {
            bookId: string;
            matches: {
                characterId: string;
                candidates: {
                    voiceId: string;
                    fromBookTitle?: string;
                    score: number;
                    factors?: components["schemas"]["MatchFactor"][];
                }[];
            }[];
        };
        MatchFactor: {
            /** @example register */
            id: string;
            /** @example Vocabulary register */
            label: string;
            score: number;
            detail?: string;
        };
        GenerationTick: {
            /**
             * @description `chapter_assembling` is emitted between the last per-group synthesis
             *     tick and `chapter_complete`, while the server concatenates the PCM,
             *     writes the WAV + segments JSON, and updates state.json. Surfaces
             *     the disk-write phase so the UI doesn't look stalled at 99 %.
             * @enum {string}
             */
            type: "progress" | "chapter_assembling" | "chapter_complete" | "chapter_failed" | "idle";
            chapterId?: number;
            /** @description null = chapter-wide tick (not character-specific). */
            characterId?: string | null;
            progress?: number;
            currentLine?: number;
            totalLines?: number;
            /** @description Only on `chapter_assembling` — number of synthesised same-speaker groups about to land on disk. */
            totalGroups?: number;
            /** @description Only on `chapter_assembling` — measured audio length about to be written. */
            durationSec?: number;
            errorReason?: string | null;
        };
        VoiceSampleRequest: {
            /**
             * @description UI-stable TTS model key. The engine prefix (coqui-, gemini-) drives provider selection server-side.
             * @enum {string}
             */
            modelKey: "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
            /** @description Frontend Voice payload (attributes drive the prebuilt-voice picker). */
            voice?: {
                id?: string;
                character?: string;
                attributes?: string[];
            };
            /**
             * @description Extra signals the server uses to pick a sensible prebuilt Gemini
             *     voice when the library `attributes` only carry personality traits
             *     (e.g. "sarcastic", "patient") rather than vocal descriptors. The
             *     description is scanned for he/she pronouns; gender + ageRange take
             *     precedence when present; tone is used as a tiebreaker. Evidence
             *     quotes (real manuscript lines) drive the sample script when
             *     present so every voice actually sounds like that character.
             */
            characterHint?: {
                description?: string;
                role?: string;
                /** @enum {string} */
                gender?: "male" | "female" | "neutral";
                /** @enum {string} */
                ageRange?: "child" | "teen" | "adult" | "elderly";
                /** @description Manuscript lines spoken by or about this character. */
                evidence?: string[];
                tone?: {
                    warmth?: number;
                    pace?: number;
                    authority?: number;
                    emotion?: number;
                };
            };
            /** @description Optional override script. Capped to ~30 words server-side to stay near 12 s. */
            text?: string;
        };
        VoiceSample: {
            /** @description Path under the server's static /audio mount; play directly with <audio>. */
            url: string;
            /** @description Computed from the synthesised PCM length. Null when the response was served from cache. */
            durationSec?: number | null;
            cached: boolean;
            /** @enum {string} */
            modelKey: "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
        };
        /**
         * @description The TTS provider voice this Voice resolves to. Computed server-side by
         *     the same picker that synthesises samples and chapters, so the value
         *     previewed in the UI matches what the user actually hears.
         */
        TtsVoiceAssignment: {
            /** @enum {string} */
            provider: "coqui" | "gemini" | "piper" | "kokoro";
            /** @description Engine-specific prebuilt voice name, e.g. 'Charon' (Gemini) or 'Claribel Dervla' (Coqui XTTS v2). */
            name: string;
            /** @description Short label for the picked voice — engine-specific. Empty/placeholder when the engine doesn't publish descriptors. */
            description: string;
        };
        Voice: {
            /** @description Stable id used to hash a TTS prebuilt voice. Defaults to character.voiceId or character.id. */
            id: string;
            character: string;
            bookTitle: string;
            bookId: string;
            attributes: string[];
            gradient: string[];
            /** @description Number of distinct books that contain this voiceId. */
            usedIn: number;
            /**
             * @description 'current' when the voice belongs to the currently-open book; 'library' otherwise.
             * @enum {string}
             */
            source: "current" | "library";
            /** @description Marker for narrator-like voices that span an entire book. */
            reusable?: boolean;
            /** @description Workspace-level pin flag from audiobook-workspace/voices.json. */
            pinned?: boolean;
            ttsVoice: components["schemas"]["TtsVoiceAssignment"];
        };
        VoiceLibraryResponse: {
            voices: components["schemas"]["Voice"][];
        };
        ChapterAudio: {
            /** @description Signed MP3/Opus URL; null while still rendering. */
            url?: string | null;
            durationSec: number;
            /** @description Pre-computed waveform envelope, typically 240 samples. */
            peaks: number[];
            /** @example 44100 */
            sampleRate?: number;
            segments?: {
                /** @description seconds */
                start?: number;
                /** @description seconds */
                end?: number;
                characterId?: string;
                sentenceId?: number;
            }[];
        };
        ChangeLogEvent: {
            /** @description Monotonic id, usually now.getTime() at write time. */
            id: number;
            /**
             * Format: date-time
             * @description ISO timestamp; absent on hand-authored fixture entries.
             */
            at?: string;
            /** @description Human-readable relative time ("Just now", "2 min ago"). Recomputed on render. */
            ts: string;
            /** @enum {string} */
            date: "today" | "yesterday" | "earlier";
            /** @enum {string} */
            type: "regenerate" | "voice_tune" | "voice_reuse" | "voice_lock" | "boundary_move" | "chapter_complete" | "chapter_failed" | "generation_started" | "cast_confirm" | "analysis_complete" | "import" | "library_add";
            title: string;
            note: string;
            /** @enum {string} */
            actor: "you" | "system";
            /** @description Bound to chapter scope when applicable. Reparse drops every event that carries this field. */
            chapterId?: number;
            revertible?: boolean;
        };
        WorkspaceChangeLogEvent: components["schemas"]["ChangeLogEvent"] & {
            bookId: string;
            bookTitle: string;
            author: string;
        };
        RevisionsResponse: {
            pending?: components["schemas"]["Revision"][];
            drift?: components["schemas"]["DriftEvent"][];
        };
        Revision: {
            id: string;
            chapterId: number;
            characterId: string;
            triggeredBy?: string;
            triggeredAgo?: string;
            oldDuration?: string;
            newDuration?: string;
            confidence?: number;
            segments: {
                id?: number;
                text?: string;
                oldDuration?: string;
                newDuration?: string;
                changed?: boolean;
                narratorOnly?: boolean;
            }[];
        };
        DriftEvent: {
            id: string;
            characterId: string;
            chapterId: number;
            /** @enum {string} */
            severity: "mild" | "moderate" | "severe";
            /** @example register */
            factor: string;
            factorLabel?: string;
            description?: string;
            metrics?: {
                current?: number;
                expected?: number;
                unit?: string;
            };
            detected?: string;
            /** @example regenerate_chapter */
            suggestedAction?: string;
        };
        Character: {
            id: string;
            name: string;
            role: string;
            color: string;
            lines?: number;
            scenes?: number;
            attributes?: string[];
            tone?: {
                warmth?: number;
                pace?: number;
                authority?: number;
                emotion?: number;
            };
            voiceId?: string;
            /** @enum {string} */
            voiceState?: "generated" | "tuned" | "reused" | "locked";
            /**
             * @description Voice gender inferred during analysis. Drives the prebuilt-voice
             *     picker so e.g. a young boy gets a male voice instead of a neutral
             *     default. Optional — older cached analyses won't have it.
             * @enum {string}
             */
            gender?: "male" | "female" | "neutral";
            /**
             * @description Coarse age bucket used as a register hint for TTS.
             * @enum {string}
             */
            ageRange?: "child" | "teen" | "adult" | "elderly";
            description?: string;
            evidence?: {
                quote?: string;
                note?: string;
            }[];
            matchedFrom?: {
                bookTitle?: string;
                confidence?: number;
            } | null;
        };
        Chapter: {
            id: number;
            title: string;
            /** @example 12:48 */
            duration: string;
            /** @enum {string} */
            state: "queued" | "in_progress" | "done" | "failed";
            progress: number;
            currentLine?: number;
            totalLines?: number;
            characters: {
                [key: string]: "queued" | "in_progress" | "done" | "skipped" | "failed";
            };
            errorReason?: string | null;
        };
        Sentence: {
            id: number;
            chapterId: number;
            text: string;
            characterId: string;
            startMs?: number;
            endMs?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merged settings + env-derived status fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
        };
    };
    putUserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsPatch"];
            };
        };
        responses: {
            /** @description Updated settings (same shape as GET) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
            /** @description Malformed body (failed schema validation) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWorkspaceChangelog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace-wide editorial activity feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: components["schemas"]["WorkspaceChangeLogEvent"][];
                    };
                };
            };
        };
    };
    getLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library tree grouped by author and series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
        };
    };
    importManuscript: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
                "application/json": {
                    text: string;
                    fileName?: string;
                };
            };
        };
        responses: {
            /** @description Parsed candidate ready for confirmation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Unsupported manuscript format */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBookRequest"];
            };
        };
        responses: {
            /** @description Book saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmBookResponse"];
                };
            };
            /** @description Missing required fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A book with this slug already exists on disk */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example slug_collision */
                        error?: string;
                        suggestedTitle?: string;
                    };
                };
            };
            /** @description Import tempId expired or already consumed */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadManuscript: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description Optional override title. */
                    title?: string;
                };
                "application/json": {
                    title?: string;
                    /** @description Inline manuscript text (markdown or plain). */
                    text: string;
                };
            };
        };
        responses: {
            /** @description Manuscript accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Unsupported manuscript format (e.g. unparseable EPUB/DOCX) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    analyseManuscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manuscriptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Final analysis payload (also delivered as the terminal SSE event) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyseResponse"];
                    "text/event-stream": components["schemas"]["AnalysePhaseEvent"] | components["schemas"]["AnalyseResponse"];
                };
            };
        };
    };
    getVoiceSample: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voiceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceSampleRequest"];
            };
        };
        responses: {
            /** @description Sample is ready (either cached or freshly synthesised) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceSample"];
                };
            };
            /** @description Invalid model key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream TTS provider is rate-limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream TTS provider failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    matchVoices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    characters: components["schemas"]["CharacterMatchInput"][];
                    /** @description Restrict candidates to a subset of the user's library. */
                    libraryVoiceIds?: string[];
                };
            };
        };
        responses: {
            /** @description Match candidates per character */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceMatchResponse"];
                };
            };
        };
    };
    streamGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description TTS model key. Local engines (coqui-*) route to the sidecar; gemini-* keys route to Google's TTS API.
                     * @enum {string}
                     */
                    modelKey: "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
                    /** @description Optional subset of chapters to (re)generate. Defaults to all chapters lacking an audio file. */
                    chapterIds?: number[];
                    /** @description Re-synthesise even if an audio file already exists on disk. */
                    force?: boolean;
                };
            };
        };
        responses: {
            /** @description Tick stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["GenerationTick"];
                };
            };
        };
    };
    getChapterAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
                chapterId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter audio metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterAudio"];
                };
            };
        };
    };
    getVoices: {
        parameters: {
            query?: {
                /** @description When set, voices belonging to that book are tagged source=current. */
                currentBookId?: string;
                /** @description TTS engine whose voice catalog is used to populate each Voice.ttsVoice. Defaults to 'coqui' (the UI's default). */
                engine?: "coqui" | "gemini" | "piper" | "kokoro";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Derived voice library, pinned first then by usage descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceLibraryResponse"];
                };
            };
        };
    };
    setVoicePin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voiceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pinned: boolean;
                };
            };
        };
        responses: {
            /** @description Pin flag updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or non-boolean `pinned` field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pollRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Outstanding revisions + drift events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionsResponse"];
                };
            };
        };
    };
}
