/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/user/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the user's account defaults + non-secret server overrides
         * @description Returns the merged user-settings document. The server reads
         *     `server/user-settings.json` (created on first GET with defaults) and
         *     layers in env-derived read-only fields: `apiKeyStatus`,
         *     `workspaceRoot`, `workspaceSource`. The Gemini API key itself is
         *     never echoed back — only the binary "is something set in .env" flag.
         */
        get: operations["getUserSettings"];
        /**
         * Update the user's account defaults + non-secret server overrides
         * @description Partial update. Only the writable fields from the request body are
         *     persisted; `apiKeyStatus`, `workspaceRoot`, `workspaceSource` are
         *     derived and silently ignored if submitted. Any field named
         *     `geminiApiKey` (or similar secret-shaped key) is also dropped — the
         *     API key never leaves `server/.env`. Changes to `sidecarUrl` take
         *     effect on the next request; `workspaceDirOverride` is persisted
         *     but requires a server restart to apply.
         */
        put: operations["putUserSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated change log across every book in the workspace
         * @description Fans out `.audiobook/change-log.json` from every book in the workspace,
         *     attaches `bookId`, `bookTitle`, and `author` to each event, and returns
         *     a page of events sorted newest-first. Books without an on-disk
         *     change-log are skipped. Backs the global Change Log view.
         *
         *     Pagination is cursor-based: pass `before` (the previous page's
         *     `nextCursor`) to fetch the next page. `totalCount` and
         *     `categoryCounts` always reflect the FULL workspace set, not just
         *     this page — the workspace Activity pills can show honest totals while
         *     the user scrolls through pages.
         */
        get: operations["getWorkspaceChangelog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List books in the on-disk workspace
         * @description Walks the workspace `books/<Author>/<Series>/<Book>/` tree and returns
         *     the grouped library used by the frontend's book-library view. Status
         *     per book is derived from the presence of `.audiobook/state.json`,
         *     `cast.json`, and the audio output count.
         */
        get: operations["getLibrary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a manuscript and stage it for confirmation
         * @description Parse-only: returns the parsed text plus best-effort author/series/title
         *     metadata, and stashes the result in memory under a short tempId. Nothing
         *     is written to disk. The frontend then renders a confirm-metadata form;
         *     on submit, POST /api/books drains the staging entry into the workspace.
         */
        post: operations["importManuscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm metadata and write a book into the workspace
         * @description Drains the staged import identified by `tempId`, writes
         *     `manuscript.<ext>` and `.audiobook/state.json` into
         *     `books/<Author>/<Series>/<Title>/`, and returns the resulting bookId +
         *     manuscriptId. Returns 409 with a `suggestedTitle` if a book with the
         *     same slug already exists.
         */
        post: operations["confirmBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manuscripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a manuscript */
        post: operations["uploadManuscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manuscripts/{manuscriptId}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run cast + chapter analysis
         * @description Streams phase progress over Server-Sent Events while the analysis
         *     runs. The final SSE event carries the full `AnalyseResponse`.
         */
        post: operations["analyseManuscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manuscripts/{manuscriptId}/analysis/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-run analysis for a subset of chapters
         * @description Runs Phase 0a (cast detection) + Phase 1 (sentence attribution)
         *     for the listed chapter ids only, merging into the existing roster
         *     and analysis cache without re-doing the whole book. Used when the
         *     user un-excludes a chapter that was excluded at confirm time.
         */
        post: operations["analyseChapterSubset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/chapters/{chapterId}/exclude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle the excluded flag on a single chapter
         * @description Updates state.json atomically and propagates the flag into the
         *     in-memory ManuscriptRecord so subsequent analysis/generation
         *     passes honour it. When `excluded` becomes true, any existing
         *     audio output for the chapter is deleted; when it becomes false
         *     the chapter is eligible for analysis-subset + audio generation
         *     again.
         */
        post: operations["setChapterExcluded"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/cover/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List OpenLibrary cover candidates for a book
         * @description Searches OpenLibrary (`/search.json?title=…&author=…`) and returns
         *     up to 6 deduped cover candidates. Powers the "Find cover image"
         *     modal on the library card + Listen header. Keyless — OpenLibrary
         *     is the upstream and rate-limits anonymously.
         */
        get: operations["getCoverCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream the cached cover image bytes
         * @description Serves the JPEG bytes for the book's currently-selected cover
         *     (`<bookDir>/.audiobook/cover.jpg`). Cached for an hour
         *     (`Cache-Control: public, max-age=3600`). Returns 404 when no
         *     cover is on disk — clients fall back to `coverGradient`.
         */
        get: operations["getCover"];
        put?: never;
        /**
         * Download and pin one of the OpenLibrary candidates as this book's cover
         * @description Re-runs the OpenLibrary search to locate the requested candidate
         *     by `openLibraryId`, downloads the JPEG to
         *     `<bookDir>/.audiobook/cover.jpg`, and patches `coverImage` onto
         *     state.json so the next library scan exposes `coverImageUrl`.
         */
        post: operations["setCover"];
        /**
         * Remove the cached cover and revert to the procedural gradient
         * @description Removes `<bookDir>/.audiobook/cover.jpg` and clears the
         *     `coverImage` field from state.json. Idempotent — succeeds even
         *     when no cover exists.
         */
        delete: operations["deleteCover"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/base": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the raw model voices the configured engines expose
         * @description Returns the catalog of unmodified model voices available across every
         *     supported TTS engine, used both by the Voices view's "Base voices"
         *     tab and by the per-cast voice-override picker in the Profile Drawer.
         *
         *     For `coqui`, the list is read from the live sidecar `GET /speakers`
         *     — entries reflect whatever XTTS v2's `speaker_manager` actually
         *     publishes today (the sidecar tolerates `name_to_id` / `speaker_names`
         *     API drift). If the sidecar is unreachable, the coqui section is
         *     empty rather than failing the whole call.
         *
         *     For `gemini`, `piper`, `kokoro`, the list comes from the
         *     engine-specific static constants in `server/src/tts/voice-mapping.ts`
         *     — these engines either ship fixed voice catalogs or aren't installed
         *     locally, so they don't depend on a running sidecar.
         */
        get: operations["getBaseVoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/{voiceId}/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synthesise a ~12-second voice preview
         * @description Renders a short sample of the voice via the configured TTS provider
         *     (free-tier Gemini). The server caches the WAV on disk keyed by
         *     `voiceId` + `modelKey`; subsequent requests with the same key return
         *     immediately with `cached: true`. The frontend plays the URL with a
         *     plain `<audio>` element.
         *
         *     When `rawEngine` + `rawSpeaker` are provided, the picker is
         *     bypassed and the named speaker is synthesised directly. This is
         *     what powers the "Base voices" tab and the family-header Play
         *     buttons — the voiceId in the path is treated as a cache scope
         *     (`raw-<engine>-<speaker>`) so unused base voices can still cache
         *     without piggy-backing on a real Voice id.
         */
        post: operations["getVoiceSample"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/voice-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match characters to existing library voices */
        post: operations["matchVoices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/generation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate chapter audio with progress streaming
         * @description Single long-running POST that streams generation progress as SSE
         *     events. Mirrors the analysis route shape (`POST /api/manuscripts/{id}/
         *     analysis`). Each `data: <json>` payload follows the GenerationTick
         *     schema. Synthesises chapters one at a time; per-chapter completion
         *     writes `audio/<chapterSlug>.mp3` + `audio/<chapterSlug>.segments.json`
         *     into the workspace book directory. Legacy `.wav` files from chapters
         *     generated before the MP3 switch keep playing — the locator probes
         *     `.mp3` first, falls back to `.wav` (see plan 28).
         */
        post: operations["streamGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/chapters/{chapterId}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a chapter's playable audio + waveform metadata */
        get: operations["getChapterAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/chapters/{chapterId}/audio/previous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the preserved prior chapter audio (for revision a/b audition)
         * @description Returns the metadata for the chapter audio that was preserved when
         *     a regeneration replaced it. Same shape as `getChapterAudio`. The
         *     revision-diff player fetches both endpoints to drive its A vs B
         *     playback. 404 when no preserved pair exists (legacy chapters or
         *     first renders).
         */
        get: operations["getChapterAudioPrevious"];
        put?: never;
        post?: never;
        /**
         * Accept the new render — discard the preserved prior audio
         * @description Deletes `audio/<slug>.previous.{mp3,wav}` and
         *     `audio/<slug>.previous.segments.json`. Idempotent: missing files
         *     are skipped. 404 only when no preserved pair existed to begin with.
         */
        delete: operations["acceptChapterRevision"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/chapters/{chapterId}/audio/previous/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject the new render — restore the preserved prior audio
         * @description Renames `audio/<slug>.previous.*` over the live names, clobbering
         *     the freshly-rendered audio. The user has chosen the prior take.
         *     409 when a generation is in flight for the book (the rename would
         *     race the write path).
         */
        post: operations["rejectChapterRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List voices derived from every confirmed cast in the workspace
         * @description Walks `books/<Author>/<Series>/<Book>/.audiobook/cast.json` for every
         *     book where `state.castConfirmed === true` and aggregates the characters
         *     into a deduplicated voice library. There is no separate voice store —
         *     a "voice" is the reusable identity of a previously-cast character. The
         *     `id` matches what the TTS layer hashes for prebuilt-voice picking, so
         *     cached samples at `/audio/voices/{id}-{modelKey}-{paramHash}.mp3`
         *     line up. The trailing hash captures the synthesis inputs so attribute
         *     edits in the profile drawer correctly bust the cache.
         */
        get: operations["getVoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/{voiceId}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Pin or unpin a voice in the workspace library
         * @description Toggles a workspace-level pin flag persisted to
         *     `audiobook-workspace/voices.json`. Pinned voices sort to the top of
         *     the library response so favourites stay at hand across books.
         */
        put: operations["setVoicePin"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/{voiceId}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set or clear the manual base-voice override on a voice family
         * @description Writes a manual base-voice override into every cast.json character
         *     whose `voiceId` (or character id, when voiceId is absent) matches the
         *     path parameter. The same voiceId can recur across a series (the
         *     character is meant to be the same identity), so one PUT propagates to
         *     every confirmed-cast book that shares it. Pass `override: null` to
         *     clear.
         *
         *     When the override's engine matches the project's active TTS engine,
         *     synthesis bypasses the attribute-driven picker (`pickVoiceForEngine`)
         *     and uses the named speaker directly. Cross-engine overrides are kept
         *     but ignored at synth time; the UI surfaces an "engine mismatch" badge.
         */
        put: operations["setVoiceOverride"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pending A/B revisions + voice-drift events
         * @description Polled every 30 s by the client, or pushed via the generation stream.
         */
        get: operations["pollRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build a sideloadable audiobook artifact (Phase A — MP3.ZIP)
         * @description Packages a finished book's per-chapter MP3 files into a single
         *     zip archive (PocketBook Reader Android sideloads MP3.ZIP, the
         *     e-reader's audiobook app on every platform accepts it). The
         *     zip carries one MP3 per non-excluded chapter, two-digit-prefixed
         *     and ID3v2.4-tagged (TIT2, TALB, TPE1, TPE2, TRCK) so PocketBook
         *     sorts and labels them correctly. Chapter audio is copied byte-
         *     for-byte via `ffmpeg -c:a copy` — no re-encode of the existing
         *     LAME VBR V2 frames.
         *
         *     Returns immediately with the freshly-created job; clients poll
         *     `getBookExport` for progress and follow `downloadUrl` once
         *     `status === 'done'`. With `destination: 'sync-folder'`, the
         *     finished archive is also copied to the user's configured
         *     `exportSyncFolder` via an atomic tmp+rename (same OneDrive-safe
         *     backoff as state.json). Refuses with `409 export_incomplete`
         *     when any non-excluded chapter lacks an `.mp3` audio file.
         */
        post: operations["createBookExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll the status of an in-flight or completed export */
        get: operations["getBookExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/exports/{exportId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream the export archive bytes
         * @description Range-aware `application/zip` (Phase A) or `audio/mp4`
         *     (Phase B M4B) stream. Phone Chrome can hit this URL directly
         *     over the LAN; the browser saves into Downloads/ and a tap
         *     opens it with PocketBook Reader.
         */
        get: operations["downloadBookExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/lan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Enumerate the server's reachable LAN URLs
         * @description Returns non-loopback IPv4 addresses the Node server is reachable
         *     on so the export modal can render a sideload URL + QR for the
         *     user's phone. Loopback (127.x) and link-local v6 (fe80::) are
         *     filtered out — they're useless for sideloading. Order matches
         *     `os.networkInterfaces()` enumeration; the modal picks the first.
         */
        get: operations["getExportLanUrls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserSettings: {
            /**
             * @description Free-text name shown in the top-bar avatar and used as the
             *     author of editorial actions in the change log. Seeded to a
             *     placeholder on first run; user can edit any time.
             */
            displayName: string;
            /**
             * @description Analysis model id from src/lib/models.ts MODEL_OPTIONS. Used as
             *     the initial value of ui.selectedModel when a book has no
             *     persisted analysis-model choice (seed-only; per-book picks win
             *     after).
             */
            defaultAnalysisModel: string;
            /**
             * @description Frontend engine group from src/lib/tts-models.ts (TtsEngineId).
             *     Used to filter the model dropdown's initial state.
             * @enum {string}
             */
            defaultTtsEngine: "local" | "gemini";
            /**
             * @description TTS model key from src/lib/tts-models.ts. Used as the initial
             *     value of ui.ttsModelKey when a book has no persisted TTS-model
             *     choice (seed-only). Default for new accounts is `kokoro-v1`.
             * @enum {string}
             */
            defaultTtsModelKey: "kokoro-v1" | "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
            /**
             * @description Overrides the LOCAL_TTS_URL env var. Re-read on every request
             *     by the sidecar provider + health probe.
             */
            sidecarUrl: string;
            /**
             * @description Analyzer dispatch. `local` routes through OllamaAnalyzer (with
             *     Gemini as automatic fallback iff GEMINI_API_KEY is set AND the
             *     local daemon is unreachable). `gemini` always goes direct.
             *     See server/src/analyzer/index.ts selectAnalyzer.
             * @enum {string}
             */
            analysisEngine: "local" | "gemini";
            /**
             * @description Base URL of the local Ollama daemon. Falls through to OLLAMA_URL
             *     env then http://localhost:11434 in the server resolver. Re-read
             *     on every analysis request, like sidecarUrl. The Ollama *model*
             *     tag is not stored separately — `defaultAnalysisModel` doubles
             *     as the Ollama tag when it has Ollama shape (contains ':').
             */
            ollamaUrl: string;
            /**
             * @description Optional override for the WORKSPACE_DIR env var. Read once at
             *     server startup — changes require a server restart to apply
             *     (UI flags this with a "restart required" badge).
             */
            workspaceDirOverride?: string | null;
            /**
             * @description Optional destination folder the audiobook-export pipeline copies
             *     finished files into (e.g. a OneDrive or Syncthing watch path
             *     mirrored to the user's phone). Null disables the "save to sync
             *     folder" tab in the export modal. The writer mkdirs on demand
             *     and uses the same OneDrive-safe atomic-rename retry as state.json.
             */
            exportSyncFolder?: string | null;
            /**
             * @description Threshold for the minor-cast fold pass at analysis time. A
             *     character whose number of attributed sentences (not words —
             *     each sentence the model assigns to that speaker counts as one
             *     "line", same as the count shown on the cast roster) is BELOW
             *     this number gets folded into the generic `Unknown male` /
             *     `Unknown female` bucket. Set to 0 to disable the line-count
             *     trigger entirely (only characters whose name begins with
             *     "Unknown" will still fold). Default 3 — i.e. a speaker who
             *     says 0, 1, or 2 sentences in the whole book doesn't warrant a
             *     dedicated voice profile.
             */
            minorCastMinLines: number;
            /**
             * @description Whether process.env.GEMINI_API_KEY is non-empty. The key value
             *     itself is never returned over the wire — the UI uses this flag
             *     to render a "set in server/.env" pill.
             * @enum {string}
             */
            readonly apiKeyStatus: "set" | "unset";
            /** @description Resolved absolute path of the active workspace root. */
            readonly workspaceRoot: string;
            /**
             * @description Where WORKSPACE_ROOT was resolved from. `override` when
             *     user-settings.json's workspaceDirOverride was used at boot,
             *     `env` when WORKSPACE_DIR was, `default` when the built-in
             *     `../audiobook-workspace` fallback applied.
             * @enum {string}
             */
            readonly workspaceSource: "env" | "default" | "override";
        };
        /**
         * @description Partial update payload. Read-only fields (apiKeyStatus,
         *     workspaceRoot, workspaceSource) are ignored. Any `geminiApiKey`-
         *     shaped field is dropped — the API key only lives in server/.env.
         */
        UserSettingsPatch: {
            displayName?: string;
            defaultAnalysisModel?: string;
            /** @enum {string} */
            defaultTtsEngine?: "local" | "gemini";
            /** @enum {string} */
            defaultTtsModelKey?: "kokoro-v1" | "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
            sidecarUrl?: string;
            /** @enum {string} */
            analysisEngine?: "local" | "gemini";
            ollamaUrl?: string;
            workspaceDirOverride?: string | null;
            exportSyncFolder?: string | null;
            minorCastMinLines?: number;
        };
        LibraryResponse: {
            authors: components["schemas"]["LibraryAuthor"][];
        };
        LibraryAuthor: {
            name: string;
            series: components["schemas"]["LibrarySeries"][];
        };
        LibrarySeries: {
            name: string;
            books: components["schemas"]["LibraryBook"][];
        };
        CoverCandidate: {
            /**
             * @description Stable identifier carried back to POST /api/books/{bookId}/cover
             *     (`cover-i:<openLibraryCoverEditionId>`).
             */
            openLibraryId: string;
            /**
             * Format: uri
             * @description Direct OpenLibrary cover URL (`/b/id/<id>-L.jpg`).
             */
            coverUrl: string;
            /** @description Optional display string — `<publisher> · <year>`. Best-effort; OpenLibrary metadata is patchy. */
            edition?: string;
        };
        LibraryBook: {
            /** @description slug(author)__slug(series)__slug(title) */
            bookId: string;
            title: string;
            author: string;
            series: string;
            /** @description Series position. Allows decimals for novellas (e.g. 1.5). */
            seriesPosition?: number | null;
            isStandalone: boolean;
            /** @enum {string} */
            status: "not_analysed" | "analysing" | "cast_pending" | "generating" | "complete" | "unreadable" | "orphaned";
            manuscriptId?: string;
            chapterCount: number;
            completedChapters: number;
            characterCount: number;
            voiceCount: number;
            matchedFromLibrary?: number;
            progress?: number;
            /** @description human-formatted total runtime, e.g. '4h 38m' */
            runtime?: string;
            /** @description human-formatted relative time, e.g. '2 min ago' */
            lastWorkedOn: string;
            coverGradient: string[];
            /**
             * Format: uri-reference
             * @description Server-relative URL for the cached cover image bytes (always
             *     `/api/books/{bookId}/cover`). Present only when the book has
             *     a cover cached on disk (`.audiobook/cover.jpg`). When
             *     absent, the UI falls back to `coverGradient`.
             */
            coverImageUrl?: string;
            pinned?: boolean;
        };
        ImportCandidate: {
            /** @enum {string} */
            format: "markdown" | "plaintext" | "epub" | "pdf";
            title: string;
            author?: string | null;
            series?: string | null;
            /** @description Series position. Allows decimals for novellas (e.g. 1.5). */
            seriesPosition?: number | null;
            sourceText: string;
            wordCount: number;
            byteSize: number;
            chapters: {
                id: number;
                title: string;
                /** @description Words in this chapter body. Lets the confirm view auto-suggest front/back-matter exclusion. */
                wordCount?: number;
            }[];
        };
        ImportResponse: {
            /** @example imp_abc123 */
            tempId: string;
            candidate: components["schemas"]["ImportCandidate"];
        };
        ConfirmBookRequest: {
            tempId: string;
            author: string;
            series?: string;
            /** @description Series position. Allows decimals for novellas (e.g. 1.5). */
            seriesPosition?: number | null;
            title: string;
            isStandalone: boolean;
            /** @description Chapter slugs to seed as excluded=true in state.json. Built client-side from the candidate.chapters[].id + title; the server re-derives the slug to match. */
            excludedSlugs?: string[];
        };
        ConfirmBookResponse: components["schemas"]["UploadResponse"] & {
            bookId: string;
            author: string;
            series: string;
            /** @description Series position. Allows decimals for novellas (e.g. 1.5). */
            seriesPosition?: number | null;
            isStandalone: boolean;
            paths: {
                bookDir: string;
                manuscript: string;
                dotAudiobook: string;
            };
        };
        UploadResponse: {
            /** @example mns_abc123 */
            manuscriptId: string;
            /** @enum {string} */
            format: "markdown" | "plaintext" | "epub" | "pdf";
            title: string;
            wordCount: number;
            byteSize: number;
            /** Format: date-time */
            uploadedAt: string;
            /** @description Normalised plain-text body. */
            sourceText: string;
        };
        AnalysePhaseEvent: {
            phaseId: number;
            progress: number;
            label?: string;
        };
        AnalyseResponse: {
            /** @example ns */
            bookId: string;
            manuscriptId: string;
            title: string;
            phaseTimings: {
                id?: number;
                label?: string;
                /** @description milliseconds */
                duration?: number;
            }[];
            characters: components["schemas"]["Character"][];
            chapters: components["schemas"]["Chapter"][];
            sentences: components["schemas"]["Sentence"][];
            /** @description Hints from a pre-pass against the user's voice library. */
            libraryMatches?: {
                characterId?: string;
                voiceId?: string;
                confidence?: number;
            }[];
        };
        CharacterMatchInput: {
            id: string;
            name: string;
            /**
             * @description Alternate forms accumulated when the user merged duplicate roster
             *     entries (mirrors Character.aliases). The matcher scores against
             *     name OR any alias on either side, so book N+1 can recognise a
             *     character last met under a different form.
             */
            aliases?: string[];
            /**
             * @description Optional tie-breaker signal (set by analysis).
             * @enum {string}
             */
            gender?: "male" | "female" | "neutral";
            /**
             * @description Optional tie-breaker signal (set by analysis).
             * @enum {string}
             */
            ageRange?: "child" | "teen" | "adult" | "elderly";
            attributes: string[];
            tone?: {
                warmth?: number;
                pace?: number;
                authority?: number;
                emotion?: number;
            };
            evidenceQuotes?: string[];
        };
        VoiceMatchResponse: {
            bookId: string;
            matches: {
                characterId: string;
                candidates: {
                    voiceId: string;
                    /** @description Library book whose confirmed cast holds this voice. Lets the client target the exact library record for the override endpoint. */
                    fromBookId?: string;
                    fromBookTitle?: string;
                    /** @description Character id within fromBookId's cast.json. Stable handle for library-cast override. */
                    fromCharacterId?: string;
                    score: number;
                    factors?: components["schemas"]["MatchFactor"][];
                }[];
            }[];
        };
        MatchFactor: {
            /** @example register */
            id: string;
            /** @example Vocabulary register */
            label: string;
            score: number;
            detail?: string;
        };
        GenerationTick: {
            /**
             * @description `chapter_assembling` is emitted between the last per-group synthesis
             *     tick and `chapter_complete`, while the server concatenates the PCM,
             *     writes the WAV + segments JSON, and updates state.json. Surfaces
             *     the disk-write phase so the UI doesn't look stalled at 99 %.
             * @enum {string}
             */
            type: "progress" | "chapter_assembling" | "chapter_complete" | "chapter_failed" | "idle";
            chapterId?: number;
            /** @description null = chapter-wide tick (not character-specific). */
            characterId?: string | null;
            progress?: number;
            currentLine?: number;
            totalLines?: number;
            /** @description Only on `chapter_assembling` — number of synthesised same-speaker groups about to land on disk. */
            totalGroups?: number;
            /** @description Only on `chapter_assembling` — measured audio length about to be written. */
            durationSec?: number;
            /**
             * @description Only on `chapter_complete` — the TTS model key that produced
             *     this chapter's audio. Carries the engine forward so the
             *     frontend can update `chapter.audioModelKey` without waiting
             *     for a state.json reload (which would otherwise let an
             *     engine-drift badge appear only after page navigation). See
             *     `docs/features/35-engine-drift-detection.md`.
             * @enum {string}
             */
            audioModelKey?: "kokoro-v1" | "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
            errorReason?: string | null;
        };
        VoiceSampleRequest: {
            /**
             * @description UI-stable TTS model key. The engine prefix (kokoro-, coqui-, gemini-) drives provider selection server-side.
             * @enum {string}
             */
            modelKey: "kokoro-v1" | "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
            /** @description Frontend Voice payload (attributes drive the prebuilt-voice picker). */
            voice?: {
                id?: string;
                character?: string;
                attributes?: string[];
            };
            /**
             * @description Extra signals the server uses to pick a sensible prebuilt Gemini
             *     voice when the library `attributes` only carry personality traits
             *     (e.g. "sarcastic", "patient") rather than vocal descriptors. The
             *     description is scanned for he/she pronouns; gender + ageRange take
             *     precedence when present; tone is used as a tiebreaker. Evidence
             *     quotes (real manuscript lines) drive the sample script when
             *     present so every voice actually sounds like that character.
             */
            characterHint?: {
                description?: string;
                role?: string;
                /** @enum {string} */
                gender?: "male" | "female" | "neutral";
                /** @enum {string} */
                ageRange?: "child" | "teen" | "adult" | "elderly";
                /** @description Manuscript lines spoken by or about this character. */
                evidence?: string[];
                tone?: {
                    warmth?: number;
                    pace?: number;
                    authority?: number;
                    emotion?: number;
                };
            };
            /** @description Optional override script. Capped to ~30 words server-side to stay near 12 s. */
            text?: string;
            /**
             * @description When set together with `rawSpeaker`, the server skips the
             *     attribute-driven prebuilt-voice picker and synthesises with the
             *     named base voice directly. Used by the Voices view's "Base voices"
             *     tab and family-header Play buttons.
             * @enum {string}
             */
            rawEngine?: "coqui" | "gemini" | "piper" | "kokoro";
            /**
             * @description Base-voice name from `GET /api/voices/base` (e.g. "Asya Anara",
             *     "Charon"). Ignored unless `rawEngine` is also set.
             */
            rawSpeaker?: string;
        };
        VoiceSample: {
            /** @description Path under the server's static /audio mount; play directly with <audio>. */
            url: string;
            /** @description Computed from the synthesised PCM length. Null when the response was served from cache. */
            durationSec?: number | null;
            cached: boolean;
            /** @enum {string} */
            modelKey: "kokoro-v1" | "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
        };
        /**
         * @description The TTS provider voice this Voice resolves to. Computed server-side by
         *     the same picker that synthesises samples and chapters, so the value
         *     previewed in the UI matches what the user actually hears.
         */
        TtsVoiceAssignment: {
            /** @enum {string} */
            provider: "coqui" | "gemini" | "piper" | "kokoro";
            /** @description Engine-specific prebuilt voice name, e.g. 'Charon' (Gemini) or 'Claribel Dervla' (Coqui XTTS v2). */
            name: string;
            /** @description Short label for the picked voice — engine-specific. Empty/placeholder when the engine doesn't publish descriptors. */
            description: string;
        };
        /**
         * @description One unmodified speaker exposed by a TTS engine. The pair (engine, name)
         *     is the stable identity — the engine routes the request to the right
         *     provider, the name is the engine-specific speaker handle (XTTS speaker
         *     name, Gemini prebuilt voice id, Piper short name, etc.). Used by the
         *     Voices view's "Base voices" tab and the Profile Drawer override picker.
         */
        BaseVoice: {
            /** @enum {string} */
            engine: "coqui" | "gemini" | "piper" | "kokoro";
            /** @description Engine-specific speaker handle, e.g. 'Asya Anara' (Coqui XTTS) or 'Charon' (Gemini). */
            name: string;
            /** @description Optional ISO 639-1 / BCP-47 hint; absent when the engine doesn't tag languages. */
            language?: string;
            /**
             * @description Engine-supplied gender hint; absent when the engine doesn't publish one (XTTS speakers don't).
             * @enum {string}
             */
            gender?: "male" | "female" | "neutral";
        };
        BaseVoiceCatalog: {
            voices: components["schemas"]["BaseVoice"][];
        };
        Voice: {
            /** @description Stable id used to hash a TTS prebuilt voice. Defaults to character.voiceId or character.id. */
            id: string;
            character: string;
            bookTitle: string;
            bookId: string;
            attributes: string[];
            gradient: string[];
            /** @description Number of distinct books that contain this voiceId. */
            usedIn: number;
            /**
             * @description 'current' when the voice belongs to the currently-open book; 'library' otherwise.
             * @enum {string}
             */
            source: "current" | "library";
            /** @description Marker for narrator-like voices that span an entire book. */
            reusable?: boolean;
            /** @description Workspace-level pin flag from audiobook-workspace/voices.json. */
            pinned?: boolean;
            ttsVoice: components["schemas"]["TtsVoiceAssignment"];
            /**
             * @description User-set TTS voice overrides per engine. Each entry pins a
             *     specific speaker for that engine; the active synth engine
             *     reads its own slot at render time and falls back to attribute
             *     inference when absent. Engine switches preserve cast
             *     assignments across engines (no need to re-cast every
             *     character when toggling Coqui ↔ Kokoro).
             *
             *     Keyed by `TtsEngine` (`coqui`, `gemini`, `piper`, `kokoro`);
             *     OpenAPI 3.0 can't constrain map keys to an enum, but the
             *     server normalises unknown keys away at read time.
             * @example {
             *       "coqui": {
             *         "name": "Asya Anara"
             *       },
             *       "kokoro": {
             *         "name": "am_onyx"
             *       }
             *     }
             */
            overrideTtsVoices?: {
                [key: string]: {
                    /** @description Engine-specific speaker handle for this engine's slot. */
                    name: string;
                };
            } | null;
            /**
             * @deprecated
             * @description DEPRECATED: superseded by `overrideTtsVoices` (plural) for
             *     multi-engine support. Server-side reads still accept this
             *     singular form for backwards compatibility with cast.json files
             *     written by older clients — they get normalised into the
             *     plural map at load time. Writes always emit `overrideTtsVoices`
             *     and may omit this field. Will be removed once all in-flight
             *     casts have been touched at least once.
             */
            overrideTtsVoice?: components["schemas"]["BaseVoice"] | null;
            /**
             * @description Series name from the book directory (`books/<Author>/<Series>/<Book>`),
             *     or null/empty for standalones. Lets the voice-family-grouped Voices
             *     view nest cast members under their book series before the book.
             */
            bookSeries?: string | null;
        };
        VoiceLibraryResponse: {
            voices: components["schemas"]["Voice"][];
        };
        ChapterAudio: {
            /** @description Signed MP3/Opus URL; null while still rendering. */
            url?: string | null;
            durationSec: number;
            /** @description Pre-computed waveform envelope, typically 240 samples. */
            peaks: number[];
            /** @example 44100 */
            sampleRate?: number;
            segments?: {
                /** @description seconds */
                start?: number;
                /** @description seconds */
                end?: number;
                characterId?: string;
                sentenceId?: number;
            }[];
        };
        ChangeLogEvent: {
            /** @description Monotonic id, usually now.getTime() at write time. */
            id: number;
            /**
             * Format: date-time
             * @description ISO timestamp; absent on hand-authored fixture entries.
             */
            at?: string;
            /** @description Human-readable relative time ("Just now", "2 min ago"). Recomputed on render. */
            ts: string;
            /** @enum {string} */
            date: "today" | "yesterday" | "earlier";
            /** @enum {string} */
            type: "regenerate" | "voice_tune" | "voice_reuse" | "voice_lock" | "boundary_move" | "chapter_complete" | "generation_run_complete" | "chapter_failed" | "generation_started" | "cast_confirm" | "analysis_complete" | "import" | "library_add" | "reparse";
            title: string;
            note: string;
            /** @enum {string} */
            actor: "you" | "system";
            /** @description Bound to chapter scope when applicable. Reparse drops every event that carries this field. */
            chapterId?: number;
            revertible?: boolean;
        };
        WorkspaceChangeLogEvent: components["schemas"]["ChangeLogEvent"] & {
            bookId: string;
            bookTitle: string;
            author: string;
        };
        RevisionsResponse: {
            pending?: components["schemas"]["Revision"][];
            drift?: components["schemas"]["DriftEvent"][];
        };
        Revision: {
            id: string;
            chapterId: number;
            characterId: string;
            triggeredBy?: string;
            triggeredAgo?: string;
            oldDuration?: string;
            newDuration?: string;
            confidence?: number;
            /** @description False while the proposed (B) audio is still rendering. The a/b player disables the B controls until this flips true. Set true once chapter_complete fires for the chapter; the generation-stream middleware flips it without waiting for the 30s revisions poll cycle. */
            playable?: boolean;
            /** @description False for legacy chapters that pre-date the rollback feature (no .previous.* pair was preserved). The a/b player renders "Original audio not preserved — review by metadata only" on the A card when this is false. */
            hasPreviousAudio?: boolean;
            segments: {
                id?: number;
                text?: string;
                oldDuration?: string;
                newDuration?: string;
                changed?: boolean;
                narratorOnly?: boolean;
            }[];
        };
        DriftEvent: {
            id: string;
            characterId: string;
            chapterId: number;
            /** @enum {string} */
            severity: "mild" | "moderate" | "severe";
            /** @example register */
            factor: string;
            factorLabel?: string;
            description?: string;
            /** @description True when the drift signal is strong enough that the user almost always wants to regenerate immediately (today: severity === 'severe'). The Drift Report surfaces these with a one-click "Auto-regen now" button that bypasses the regen-modal confirmation. Moderate / mild events leave this unset; the manual regen flow still applies. */
            autoQueueable?: boolean;
            metrics?: {
                current?: number;
                expected?: number;
                unit?: string;
            };
            detected?: string;
            /** @example regenerate_chapter */
            suggestedAction?: string;
        };
        Character: {
            id: string;
            name: string;
            role: string;
            color: string;
            lines?: number;
            scenes?: number;
            attributes?: string[];
            /**
             * @description Alternate names this character is known by. Populated when the
             *     user merges a duplicate roster entry (e.g. "Sophie" merged into
             *     "Sophie Foster" adds "Sophie" here). Surfaced to the voice
             *     matcher so the same person can be recognised when later books
             *     in a series detect the character under a different form.
             */
            aliases?: string[];
            tone?: {
                warmth?: number;
                pace?: number;
                authority?: number;
                emotion?: number;
            };
            voiceId?: string;
            /** @enum {string} */
            voiceState?: "generated" | "tuned" | "reused" | "locked";
            /**
             * @description Voice gender inferred during analysis. Drives the prebuilt-voice
             *     picker so e.g. a young boy gets a male voice instead of a neutral
             *     default. Optional — older cached analyses won't have it.
             * @enum {string}
             */
            gender?: "male" | "female" | "neutral";
            /**
             * @description Coarse age bucket used as a register hint for TTS.
             * @enum {string}
             */
            ageRange?: "child" | "teen" | "adult" | "elderly";
            description?: string;
            evidence?: {
                quote?: string;
                note?: string;
            }[];
            matchedFrom?: {
                /** @description Library book whose confirmed cast holds the matched voice. Required for the library-cast override flow. */
                bookId?: string;
                /** @description Character id within bookId's cast.json. Required for the library-cast override flow. */
                characterId?: string;
                bookTitle?: string;
                confidence?: number;
            } | null;
        };
        Chapter: {
            id: number;
            title: string;
            /** @example 12:48 */
            duration: string;
            /** @enum {string} */
            state: "queued" | "in_progress" | "done" | "failed";
            progress: number;
            currentLine?: number;
            totalLines?: number;
            characters: {
                [key: string]: "queued" | "in_progress" | "done" | "skipped" | "failed";
            };
            errorReason?: string | null;
            /** @description When true, this chapter is skipped by both analysis (Phase 0a + Phase 1) and audio generation. Typically front- or back-matter like Dedication, Copyright, About the Author. */
            excluded?: boolean;
            /**
             * @description TTS model key that produced this chapter's existing audio
             *     file. Stamped at render time and backfilled from the
             *     segments file for legacy chapters. Absent on never-rendered
             *     chapters. The frontend compares against the project's
             *     current `ui.ttsModelKey` to surface engine-drift badges (see
             *     `docs/features/35-engine-drift-detection.md`).
             * @enum {string}
             */
            audioModelKey?: "kokoro-v1" | "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
            /**
             * Format: date-time
             * @description ISO timestamp from when the audio was synthesised. Mirrors
             *     the segments file's `synthesizedAt`. Surfaces alongside the
             *     drift badge so the user can see how stale the rendered audio
             *     is.
             */
            audioRenderedAt?: string;
        };
        Sentence: {
            id: number;
            chapterId: number;
            text: string;
            characterId: string;
            startMs?: number;
            endMs?: number;
        };
        BookExportRequest: {
            /**
             * @description Container format. `mp3-zip` packages per-chapter MP3s into
             *     a zip — universal compatibility, no re-encode (the LAME
             *     VBR V2 frames round-trip byte-identical). `m4b` produces
             *     a single AAC-LC file at 96 kbps mono 44.1 kHz with
             *     QuickTime chapter atoms; PocketBook surfaces it under
             *     Audiobooks with chapter UI + resume position. M4B
             *     re-encodes from MP3 → AAC. `mp3-folder` writes the per-
             *     chapter MP3s into a sub-folder named after the book
             *     (each tagged with the same ID3v2 + optional APIC cover
             *     as the zip variant) — the folder-scanning audiobook apps
             *     (Smart AudioBook Player, Audiobookshelf, BookPlayer via
             *     Files import) pick up a folder per book. `mp3-folder` is
             *     only valid with `destination: sync-folder` since the
             *     download endpoint serves single files.
             * @enum {string}
             */
            format: "mp3-zip" | "m4b" | "mp3-folder";
            /**
             * @description `download` stages the file under the book's `.audiobook/exports/`
             *     for the user to pull via `downloadBookExport`. `sync-folder`
             *     additionally copies the finished archive into the user's
             *     configured `exportSyncFolder` (e.g. a OneDrive watch path) so
             *     it lands on their phone via sync. Requires `exportSyncFolder`
             *     to be set; the request 400s otherwise. `mp3-folder` requires
             *     this to be `sync-folder` (the download endpoint serves single
             *     files, not directory trees).
             * @enum {string}
             */
            destination: "download" | "sync-folder";
        };
        BookExportJob: {
            /** @description Server-generated export id */
            id: string;
            bookId: string;
            /** @enum {string} */
            format: "mp3-zip" | "m4b" | "mp3-folder";
            /** @enum {string} */
            destination: "download" | "sync-folder";
            /** @enum {string} */
            status: "queued" | "in_progress" | "done" | "failed";
            /** @description e.g. 'The Northern Star.zip' */
            filename: string;
            /** @description Final size once status === 'done'. */
            sizeBytes?: number | null;
            /** @description 0..1 while in_progress; null otherwise. */
            progress?: number | null;
            /** @description Set once status === 'done' AND destination === 'download'. */
            downloadUrl?: string | null;
            /** @description Absolute path the archive was copied to when destination === 'sync-folder'. */
            syncPath?: string | null;
            /** @description Human-readable failure reason; populated when status === 'failed'. */
            errorReason?: string | null;
            /** @description ISO timestamp */
            createdAt: string;
            /** @description ISO timestamp once status leaves in_progress. */
            completedAt?: string | null;
        };
        ExportLanInfo: {
            /** @description The Node server's listening port (8080 by default). */
            port: number;
            urls: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merged settings + env-derived status fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
        };
    };
    putUserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsPatch"];
            };
        };
        responses: {
            /** @description Updated settings (same shape as GET) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
            /** @description Malformed body (failed schema validation) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWorkspaceChangelog: {
        parameters: {
            query?: {
                /** @description Page size. Defaults to 50; capped at 200. */
                limit?: number;
                /**
                 * @description ISO timestamp cursor. Only events strictly older than this land
                 *     in the page. Omit on the first request; pass `nextCursor` from
                 *     the previous response thereafter.
                 */
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of workspace-wide editorial activity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: components["schemas"]["WorkspaceChangeLogEvent"][];
                        /**
                         * @description ISO timestamp of the last event in this page when more
                         *     events follow it; `null` when this page is the tail.
                         */
                        nextCursor: string | null;
                        /** @description Total events across the workspace (all pages). */
                        totalCount: number;
                        categoryCounts: {
                            voice: number;
                            generation: number;
                            manuscript: number;
                            cast: number;
                        };
                    };
                };
            };
        };
    };
    getLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library tree grouped by author and series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
        };
    };
    importManuscript: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
                "application/json": {
                    text: string;
                    fileName?: string;
                };
            };
        };
        responses: {
            /** @description Parsed candidate ready for confirmation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Unsupported manuscript format */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBookRequest"];
            };
        };
        responses: {
            /** @description Book saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmBookResponse"];
                };
            };
            /** @description Missing required fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A book with this slug already exists on disk */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example slug_collision */
                        error?: string;
                        suggestedTitle?: string;
                    };
                };
            };
            /** @description Import tempId expired or already consumed */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadManuscript: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description Optional override title. */
                    title?: string;
                };
                "application/json": {
                    title?: string;
                    /** @description Inline manuscript text (markdown or plain). */
                    text: string;
                };
            };
        };
        responses: {
            /** @description Manuscript accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Unsupported manuscript format (e.g. unparseable EPUB/DOCX) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    analyseManuscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manuscriptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Final analysis payload (also delivered as the terminal SSE event) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyseResponse"];
                    "text/event-stream": components["schemas"]["AnalysePhaseEvent"] | components["schemas"]["AnalyseResponse"];
                };
            };
        };
    };
    analyseChapterSubset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manuscriptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Chapter ids to re-run analysis for. Must reference chapters already in the manuscript record. */
                    chapterIds: number[];
                    /** @description Optional model id override (matches the full-book endpoint). */
                    model?: string;
                };
            };
        };
        responses: {
            /** @description SSE stream identical in shape to the full-book analysis route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["AnalysePhaseEvent"] | components["schemas"]["AnalyseResponse"];
                };
            };
        };
    };
    setChapterExcluded: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
                chapterId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    excluded: boolean;
                };
            };
        };
        responses: {
            /** @description Updated chapter entry from state.json */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        title: string;
                        slug: string;
                        excluded: boolean;
                    };
                };
            };
            /** @description Book or chapter not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCoverCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candidate list (may be empty when OpenLibrary has no match) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        candidates: components["schemas"]["CoverCandidate"][];
                    };
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OpenLibrary unreachable, timed out, or returned malformed JSON */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description Book has no cached cover */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Stable id from `CoverCandidate.openLibraryId` (e.g. `cover-i:123456`). */
                    openLibraryId: string;
                };
            };
        };
        responses: {
            /** @description Cover saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri-reference */
                        coverImageUrl: string;
                    };
                };
            };
            /** @description Missing or malformed `openLibraryId` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Book not found OR candidate no longer in the live OpenLibrary result set */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OpenLibrary unreachable, timed out, oversized, or returned a non-image response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cover removed (or was never present) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBaseVoices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merged base-voice catalog across all engines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseVoiceCatalog"];
                };
            };
        };
    };
    getVoiceSample: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voiceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceSampleRequest"];
            };
        };
        responses: {
            /** @description Sample is ready (either cached or freshly synthesised) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceSample"];
                };
            };
            /** @description Invalid model key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream TTS provider is rate-limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream TTS provider failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    matchVoices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    characters: components["schemas"]["CharacterMatchInput"][];
                    /** @description Restrict candidates to a subset of the user's library. */
                    libraryVoiceIds?: string[];
                };
            };
        };
        responses: {
            /** @description Match candidates per character */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceMatchResponse"];
                };
            };
        };
    };
    streamGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description TTS model key. Local engines (kokoro-, coqui-) route to the sidecar; gemini-* keys route to Google's TTS API.
                     * @enum {string}
                     */
                    modelKey: "kokoro-v1" | "coqui-xtts-v2" | "gemini-2.5-flash" | "gemini-3.1-flash";
                    /** @description Optional subset of chapters to (re)generate. Defaults to all chapters lacking an audio file. */
                    chapterIds?: number[];
                    /** @description Re-synthesise even if an audio file already exists on disk. */
                    force?: boolean;
                };
            };
        };
        responses: {
            /** @description Tick stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["GenerationTick"];
                };
            };
        };
    };
    getChapterAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
                chapterId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter audio metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterAudio"];
                };
            };
        };
    };
    getChapterAudioPrevious: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
                chapterId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preserved chapter audio metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterAudio"];
                };
            };
            /** @description No preserved audio for this chapter */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptChapterRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
                chapterId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preserved pair removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No preserved audio to delete */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejectChapterRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
                chapterId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preserved pair restored over live names */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No preserved audio to restore */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Generation is in flight for this book — restore would race the write path */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVoices: {
        parameters: {
            query?: {
                /** @description When set, voices belonging to that book are tagged source=current. */
                currentBookId?: string;
                /** @description TTS engine whose voice catalog is used to populate each Voice.ttsVoice. Defaults to 'coqui' (the UI's default). */
                engine?: "coqui" | "gemini" | "piper" | "kokoro";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Derived voice library, pinned first then by usage descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceLibraryResponse"];
                };
            };
        };
    };
    setVoicePin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voiceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pinned: boolean;
                };
            };
        };
        responses: {
            /** @description Pin flag updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or non-boolean `pinned` field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setVoiceOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voiceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    override: components["schemas"]["BaseVoice"] | null;
                };
            };
        };
        responses: {
            /** @description Override written (or cleared) on every matching cast.json entry */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Body is missing or malformed (override must be a BaseVoice or null) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No character with that voiceId exists in any confirmed cast */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pollRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Outstanding revisions + drift events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionsResponse"];
                };
            };
        };
    };
    createBookExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookExportRequest"];
            };
        };
        responses: {
            /** @description Export job created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookExportJob"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description One or more non-excluded chapters lack a `.mp3` audio file */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        error: "export_incomplete";
                        missing: string[];
                    };
                };
            };
        };
    };
    getBookExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
                exportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current job state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookExportJob"];
                };
            };
            /** @description Job id unknown */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    downloadBookExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
                exportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archive bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial content (Range request) */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job id unknown or staging file missing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getExportLanUrls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LAN URL list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportLanInfo"];
                };
            };
        };
    };
}
