/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/manuscripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a manuscript */
        post: operations["uploadManuscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manuscripts/{manuscriptId}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run cast + chapter analysis
         * @description Streams phase progress over Server-Sent Events while the analysis
         *     runs. The final SSE event carries the full `AnalyseResponse`.
         */
        post: operations["analyseManuscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/voice-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match characters to existing library voices */
        post: operations["matchVoices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/generation/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kick off audiobook generation jobs */
        post: operations["startGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/generation/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generation progress stream (SSE / WebSocket) */
        get: operations["streamGeneration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/chapters/{chapterId}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a chapter's playable audio + waveform metadata */
        get: operations["getChapterAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pending A/B revisions + voice-drift events
         * @description Polled every 30 s by the client, or pushed via the generation stream.
         */
        get: operations["pollRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UploadResponse: {
            /** @example mns_abc123 */
            manuscriptId: string;
            /** @enum {string} */
            format: "markdown" | "plaintext" | "epub" | "pdf";
            title: string;
            wordCount: number;
            byteSize: number;
            /** Format: date-time */
            uploadedAt: string;
            /** @description Normalised plain-text body. */
            sourceText: string;
        };
        AnalysePhaseEvent: {
            phaseId: number;
            progress: number;
            label?: string;
        };
        AnalyseResponse: {
            /** @example ns */
            bookId: string;
            manuscriptId: string;
            title: string;
            phaseTimings: {
                id?: number;
                label?: string;
                /** @description milliseconds */
                duration?: number;
            }[];
            characters: components["schemas"]["Character"][];
            chapters: components["schemas"]["Chapter"][];
            sentences: components["schemas"]["Sentence"][];
            /** @description Hints from a pre-pass against the user's voice library. */
            libraryMatches?: {
                characterId?: string;
                voiceId?: string;
                confidence?: number;
            }[];
        };
        CharacterMatchInput: {
            id: string;
            attributes: string[];
            tone?: {
                warmth?: number;
                pace?: number;
                authority?: number;
                emotion?: number;
            };
            evidenceQuotes?: string[];
        };
        VoiceMatchResponse: {
            bookId: string;
            matches: {
                characterId: string;
                candidates: {
                    voiceId: string;
                    fromBookTitle?: string;
                    score: number;
                    factors?: components["schemas"]["MatchFactor"][];
                }[];
            }[];
        };
        MatchFactor: {
            /** @example register */
            id: string;
            /** @example Vocabulary register */
            label: string;
            score: number;
            detail?: string;
        };
        GenerationTick: {
            /** @enum {string} */
            type: "progress" | "chapter_complete" | "chapter_failed" | "idle";
            chapterId?: number;
            /** @description null = chapter-wide tick (not character-specific). */
            characterId?: string | null;
            progress?: number;
            currentLine?: number;
            totalLines?: number;
            errorReason?: string | null;
        };
        ChapterAudio: {
            /** @description Signed MP3/Opus URL; null while still rendering. */
            url?: string | null;
            durationSec: number;
            /** @description Pre-computed waveform envelope, typically 240 samples. */
            peaks: number[];
            /** @example 44100 */
            sampleRate?: number;
            segments?: {
                /** @description seconds */
                start?: number;
                /** @description seconds */
                end?: number;
                characterId?: string;
                sentenceId?: number;
            }[];
        };
        RevisionsResponse: {
            pending?: components["schemas"]["Revision"][];
            drift?: components["schemas"]["DriftEvent"][];
        };
        Revision: {
            id: string;
            chapterId: number;
            characterId: string;
            triggeredBy?: string;
            triggeredAgo?: string;
            oldDuration?: string;
            newDuration?: string;
            confidence?: number;
            segments: {
                id?: number;
                text?: string;
                oldDuration?: string;
                newDuration?: string;
                changed?: boolean;
                narratorOnly?: boolean;
            }[];
        };
        DriftEvent: {
            id: string;
            characterId: string;
            chapterId: number;
            /** @enum {string} */
            severity: "mild" | "moderate" | "severe";
            /** @example register */
            factor: string;
            factorLabel?: string;
            description?: string;
            metrics?: {
                current?: number;
                expected?: number;
                unit?: string;
            };
            detected?: string;
            /** @example regenerate_chapter */
            suggestedAction?: string;
        };
        Character: {
            id: string;
            name: string;
            role: string;
            color: string;
            lines?: number;
            scenes?: number;
            attributes?: string[];
            tone?: {
                warmth?: number;
                pace?: number;
                authority?: number;
                emotion?: number;
            };
            voiceId?: string;
            /** @enum {string} */
            voiceState?: "generated" | "tuned" | "reused" | "locked";
            description?: string;
            evidence?: {
                quote?: string;
                note?: string;
            }[];
            matchedFrom?: {
                bookTitle?: string;
                confidence?: number;
            } | null;
        };
        Chapter: {
            id: number;
            title: string;
            /** @example 12:48 */
            duration: string;
            /** @enum {string} */
            state: "queued" | "in_progress" | "done" | "failed";
            progress: number;
            currentLine?: number;
            totalLines?: number;
            characters: {
                [key: string]: "queued" | "in_progress" | "done" | "skipped" | "failed";
            };
            errorReason?: string | null;
        };
        Sentence: {
            id: number;
            chapterId: number;
            text: string;
            characterId: string;
            startMs?: number;
            endMs?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    uploadManuscript: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description Optional override title. */
                    title?: string;
                };
                "application/json": {
                    title?: string;
                    /** @description Inline manuscript text (markdown or plain). */
                    text: string;
                };
            };
        };
        responses: {
            /** @description Manuscript accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Unsupported manuscript format (e.g. unparseable EPUB/DOCX) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    analyseManuscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manuscriptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Final analysis payload (also delivered as the terminal SSE event) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyseResponse"];
                    "text/event-stream": components["schemas"]["AnalysePhaseEvent"] | components["schemas"]["AnalyseResponse"];
                };
            };
        };
    };
    matchVoices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    characters: components["schemas"]["CharacterMatchInput"][];
                    /** @description Restrict candidates to a subset of the user's library. */
                    libraryVoiceIds?: string[];
                };
            };
        };
        responses: {
            /** @description Match candidates per character */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceMatchResponse"];
                };
            };
        };
    };
    startGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generation queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tick stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["GenerationTick"];
                };
            };
        };
    };
    getChapterAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
                chapterId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter audio metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterAudio"];
                };
            };
        };
    };
    pollRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Outstanding revisions + drift events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionsResponse"];
                };
            };
        };
    };
}
