/* Plan 60 — real-binary integration test for parseMobi.
 *
 * The sibling mobi.test.ts mocks @lingo-reader/mobi-parser so every
 * assertion exercises a specific contract under controlled inputs.
 * This file does the opposite — calls the REAL upstream parser against
 * Calibre-generated `sample.mobi` + `sample.azw3` binaries to lock the
 * integration contract end-to-end.
 *
 * Calibre is a per-developer install. The fixtures live under
 * server/src/parsers/__fixtures__/ and are generated by
 * `node scripts/gen-parser-fixtures.mjs` (which probes for
 * `ebook-convert` on PATH and skips MOBI/AZW3 generation cleanly
 * when Calibre is absent). When the fixtures are missing this suite
 * skips with a clear message via `describe.skipIf` so a fresh-clone
 * dev environment still passes `npm run verify`.
 *
 * Source EPUB: Jane Doe / "The Solway Light" / series "Solway Bay" #2,
 * defined in scripts/gen-parser-fixtures.mjs#buildEpub. The MOBI/AZW3
 * binaries are converted from that EPUB, so we assert the same title +
 * author come through the real parser.
 *
 * Pairs with docs/features/60-real-binary-parser-fixtures.md +
 * docs/features/archive/52-mobi-parsing.md.
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { parseMobi } from './mobi.js';

const here = dirname(fileURLToPath(import.meta.url));
const mobiPath = resolve(here, '__fixtures__/sample.mobi');
const azw3Path = resolve(here, '__fixtures__/sample.azw3');

const hasMobi = existsSync(mobiPath);
const hasAzw3 = existsSync(azw3Path);

/* describe.skipIf — the entire suite no-ops when Calibre hasn't been
   run. We emit the missing-Calibre breadcrumb at import time so the
   verify log shows WHY the suite is empty rather than silently
   producing zero specs. */
if (!hasMobi || !hasAzw3) {
  // eslint-disable-next-line no-console
  console.warn(
    '[mobi-real-fixtures] Calibre-generated sample.mobi / sample.azw3 ' +
      'missing — skipping real-binary integration tests. Run ' +
      '`node scripts/gen-parser-fixtures.mjs` after installing Calibre ' +
      '(https://calibre-ebook.com/download) to enable this suite.',
  );
}

describe.skipIf(!hasMobi)('parseMobi — real Calibre-generated sample.mobi', () => {
  it('parses the real Mobipocket binary without throwing', async () => {
    const buf = readFileSync(mobiPath);
    const out = await parseMobi(buf, { fileName: 'sample.mobi' });
    expect(out.format).toBe('mobi');
  });

  it('extracts dc:title from the converted EPUB', async () => {
    const buf = readFileSync(mobiPath);
    const out = await parseMobi(buf, { fileName: 'sample.mobi' });
    /* The source EPUB's <dc:title> is "The Solway Light"
       (scripts/gen-parser-fixtures.mjs#buildEpub). Calibre preserves
       this through ebook-convert. */
    expect(out.title).toBe('The Solway Light');
  });

  it('extracts dc:creator as the author', async () => {
    const buf = readFileSync(mobiPath);
    const out = await parseMobi(buf, { fileName: 'sample.mobi' });
    expect(out.author).toBe('Jane Doe');
  });

  it('produces at least one chapter with body text', async () => {
    const buf = readFileSync(mobiPath);
    const out = await parseMobi(buf, { fileName: 'sample.mobi' });
    expect(out.chapters.length).toBeGreaterThanOrEqual(1);
    /* The EPUB chapters carry the phrase "The tower stood at the
       edge of the world." in chapter1. Calibre's MOBI conversion
       reflows the text but preserves the words. */
    const allBody = out.chapters.map((c) => c.body).join('\n');
    expect(allBody).toMatch(/tower stood at the edge of the world/);
  });
});

describe.skipIf(!hasAzw3)('parseMobi — real Calibre-generated sample.azw3', () => {
  it('parses the real KF8/AZW3 binary without throwing', async () => {
    const buf = readFileSync(azw3Path);
    const out = await parseMobi(buf, { fileName: 'sample.azw3' });
    expect(out.format).toBe('mobi');
  });

  it('extracts dc:title from the converted EPUB', async () => {
    const buf = readFileSync(azw3Path);
    const out = await parseMobi(buf, { fileName: 'sample.azw3' });
    expect(out.title).toBe('The Solway Light');
  });

  it('extracts dc:creator as the author', async () => {
    const buf = readFileSync(azw3Path);
    const out = await parseMobi(buf, { fileName: 'sample.azw3' });
    expect(out.author).toBe('Jane Doe');
  });

  it('produces at least one chapter with body text', async () => {
    const buf = readFileSync(azw3Path);
    const out = await parseMobi(buf, { fileName: 'sample.azw3' });
    expect(out.chapters.length).toBeGreaterThanOrEqual(1);
    const allBody = out.chapters.map((c) => c.body).join('\n');
    expect(allBody).toMatch(/tower stood at the edge of the world/);
  });
});
