// Shared reader for the worktree slot marker that scripts/wt-new.mjs stamps
// into the env files it generates. Lives here, in a leaf module, so both
// wt-new.mjs (which allocates slots) and wt-list.mjs (which reports them)
// read the marker through the SAME code — wt-new.mjs already imports
// parseWorktreePorcelain from wt-list.mjs, so putting the reader in either
// of those two would close an import cycle between them.
//
// #3052: wt-list.mjs used to print the worktree's position in `git worktree
// list` as its "slot", which is exactly the count-based premise wt-new.mjs
// stopped using — the diagnostic denied the collision it exists to reveal.

import { existsSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

// Every generated file that carries the slot marker, relative to a worktree
// root. BOTH are scanned and their claims unioned, deliberately:
// `.env.local`'s own generated header says "safe to delete" (and it is, for
// Vite), but `server/.env` carries the identical marker AND the PORT /
// LOCAL_TTS_PORT the server and sidecar actually bind. Reading only
// `.env.local` meant deleting the file a header invites you to delete
// silently surrendered a slot claim while the tree stayed bound to its
// ports, re-opening #3052's collision.
//
// The risk here is asymmetric, and the union is the safe side of it: a
// false positive (a stale file claiming a slot nothing uses) wastes a slot
// NUMBER, of which there is no shortage; a false negative re-creates the
// data hazard — two lanes on one port, one lane's Vite proxying /api into
// the other lane's server and workspace.
export const SLOT_CLAIM_FILES = ['.env.local', 'server/.env'];

// Extract the slot number from a generated env file's header comment:
//   "# Generated by scripts/wt-new.mjs — worktree slot 2 (branch ...)"
//
// The marker is generated as line 1, but line 1 is NOT where the search
// stops. `.env.local`'s own header says "Safe to edit", and CLAUDE.md's
// "Worktree setup" step 5 instructs operators to hand-write these files for
// tool-made worktrees — so a prepended lane note or a leading blank line is
// an expected input, not a malformed one, and a first-line-only read
// answered `null` for a tree that was very much holding its slot.
//
// So: scan the LEADING COMMENT BLOCK — blank lines and `#` lines from the
// top — and stop at the first setting line (`KEY=value`). That keeps the
// property the first-line rule was protecting (a "worktree slot 9" phrase
// in a note further down, below the settings, is not mistaken for the
// marker) while tolerating anything prepended above the marker.
//
// Returns the slot number, or null when no marker is found in that block.
export function extractSlotFromEnvLocal(envContent) {
  for (const line of envContent.split(/\r?\n/)) {
    const trimmed = line.trim();
    // A blank line or a comment keeps the header block open; anything else
    // (the first KEY=value) closes it.
    // (A UTF-8 BOM ahead of the `#` is stripped by trim(), which counts
    // U+FEFF as whitespace \u2014 so a BOM'd file still reads as a comment line.)
    if (trimmed !== '' && !trimmed.startsWith('#')) return null;
    const match = /worktree slot (\d+)/.exec(line);
    if (match) return parseInt(match[1], 10);
  }
  return null;
}

// The primary checkout is a KNOWN, EXPECTED non-claimant, and callers have to
// tell it apart from a linked worktree that lost its marker.
//
// It never carries a wt-new-generated env file: wt-new.mjs only ever writes
// into the worktree it creates, so the primary checkout's `server/.env` is the
// hand-written one every real clone has (it is where GEMINI_API_KEY lives) and
// carries no slot marker. It is also structurally safe — it is slot 0, and
// allocateNextSlot starts at 1, so its slot can never be re-issued. Counting
// it as a lost claim made the "no readable marker" warning fire on 100% of
// real runs, and assert that the one guaranteed-safe tree was at risk.
//
// Detected from the tree itself, not from its position in `git worktree list`:
// a linked worktree's `.git` is a FILE containing `gitdir: …`, the primary
// checkout's is a DIRECTORY. That is a fact about the tree rather than an
// inference from enumeration order — the same class of premise #3052 was.
export function isPrimaryCheckout(treePath) {
  try {
    return statSync(join(treePath, '.git')).isDirectory();
  } catch {
    // No .git at all (a fixture directory, a removed tree): not the primary.
    return false;
  }
}

// Every SLOT_CLAIM_FILES entry that exists in a worktree, in SLOT_CLAIM_FILES
// order, as { relative, path, content }. `content` is null when the file
// exists but could not be read (permissions, a half-written file) — the entry
// is still returned, so a caller counting "generated files present" is not
// fooled by an unreadable one.
//
// Shared so every consumer reads the SAME set of files: readSlotClaims below
// and wt-list.mjs's port columns both go through here. wt-list used to read
// only `.env.local` for its ports, so a tree whose (deletable) `.env.local`
// was gone reported `PORT=(default)` while its server stayed bound to the
// slot's port — the slot column's own bug, one column over.
export function readClaimFiles(treePath) {
  const files = [];
  for (const relative of SLOT_CLAIM_FILES) {
    const filePath = join(treePath, ...relative.split('/'));
    if (!existsSync(filePath)) continue;
    let content = null;
    try {
      content = readFileSync(filePath, 'utf8');
    } catch {
      content = null;
    }
    files.push({ relative, path: filePath, content });
  }
  return files;
}

// Slots claimed by one worktree, read from every file in SLOT_CLAIM_FILES.
// `present` counts how many of those files exist, so a caller can tell
// "this tree claims nothing because it was never configured" apart from
// "this tree has a generated file we could not read a slot out of" — the
// second is a silent detection failure and gets surfaced, not swallowed.
export function readSlotClaims(treePath) {
  const slots = new Set();
  const files = readClaimFiles(treePath);
  for (const file of files) {
    if (file.content === null) continue;
    const slot = extractSlotFromEnvLocal(file.content);
    if (slot !== null) slots.add(slot);
  }
  return { slots: Array.from(slots).sort((a, b) => a - b), present: files.length };
}
