#!/usr/bin/env node
// Spawn a fresh git worktree on a new branch with non-colliding dev-server
// ports, so multiple Claude Code sessions can run in parallel against this
// repo without fighting over :5173 / :8080 / :9000 / :5174.
//
// Usage:
//   node scripts/wt-new.mjs <type>/<scope>-<slug> [--from <base-branch>] [--no-install]
//
// Example:
//   node scripts/wt-new.mjs feat/server-batch-retry
//   node scripts/wt-new.mjs fix/frontend-toolbar --from main
//   node scripts/wt-new.mjs chore/frontend-tidy --no-install
//
// What it does:
//   1. Validates the branch name (CONTRIBUTING.md "Branch naming").
//   2. Picks a port-offset slot from existing worktree count (slot 0 = main).
//   3. Creates ../wt-<slug> via `git worktree add -b <branch> <path> <base>`.
//   4. Writes <worktree>/.env.local with VITE_PORT / PORT / VITE_API_PORT /
//      LOCAL_TTS_PORT / PLAYWRIGHT_PORT for this slot.
//   5. Runs `npm install` (root, which also activates husky hooks via the
//      `prepare` script) + `npm install --prefix server` inside the worktree
//      so it's ready for `npm run dev` / `npm run verify` immediately. Pass
//      `--no-install` to skip both — falls back to printing the commands.
//   6. Prints a copy-pasteable launch block.
//
// See CONTRIBUTING.md "Running multiple Claude Code conversations" for the
// scope-discipline + GPU-coordination caveats.

import { spawnSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { parseBranchName } from './lib/branch-name.mjs';

const BASE_PORTS = {
  VITE_PORT: 5173,
  PORT: 8080,
  VITE_API_PORT: 8080, // matches PORT — both point at the same server
  LOCAL_TTS_PORT: 9000,
  PLAYWRIGHT_PORT: 5174,
};
const PORT_STEP = 10;

function usage(extra) {
  const lines = [
    'Usage: node scripts/wt-new.mjs <type>/<scope>-<slug> [--from <base-branch>]',
    '',
    'Example:',
    '  node scripts/wt-new.mjs feat/server-batch-retry',
    '  node scripts/wt-new.mjs fix/frontend-toolbar --from main',
    '',
    'See CONTRIBUTING.md "Branch naming" for the type+scope vocabulary.',
  ];
  if (extra) lines.unshift(`Error: ${extra}`, '');
  return lines.join('\n');
}

export function parseArgs(argv) {
  const args = { branch: null, from: 'main', install: true };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--from') {
      args.from = argv[++i];
      if (!args.from) throw new Error('--from requires a value');
    } else if (a === '--no-install') {
      args.install = false;
    } else if (a === '-h' || a === '--help') {
      args.help = true;
    } else if (a.startsWith('--')) {
      throw new Error(`unknown flag: ${a}`);
    } else if (!args.branch) {
      args.branch = a;
    } else {
      throw new Error(`unexpected positional argument: ${a}`);
    }
  }
  return args;
}

function gitOrThrow(args, opts = {}) {
  const result = spawnSync('git', args, { encoding: 'utf8', ...opts });
  if (result.error) throw new Error(`git ${args.join(' ')}: ${result.error.message}`);
  if (result.status !== 0) {
    throw new Error(`git ${args.join(' ')} failed (exit ${result.status}):\n${result.stderr || result.stdout}`);
  }
  return result.stdout;
}

export function countExistingWorktrees() {
  // `git worktree list --porcelain` emits a `worktree <path>` line per tree.
  const out = gitOrThrow(['worktree', 'list', '--porcelain']);
  return out.split(/\r?\n/).filter((line) => line.startsWith('worktree ')).length;
}

export function computePorts(slot) {
  if (!Number.isInteger(slot) || slot < 0) {
    throw new Error(`slot must be a non-negative integer, got ${slot}`);
  }
  const out = {};
  for (const [key, base] of Object.entries(BASE_PORTS)) {
    out[key] = base + slot * PORT_STEP;
  }
  return out;
}

export function renderEnvLocal({ slot, branch, ports }) {
  const lines = [
    `# Generated by scripts/wt-new.mjs — worktree slot ${slot} (branch ${branch}).`,
    `# Per-worktree port assignments so multiple parallel Claude Code sessions`,
    `# can run \`npm run dev\` / \`npm run test:e2e\` without colliding on ports.`,
    `# Safe to edit; safe to delete (defaults from vite.config.ts / server / sidecar apply).`,
    ``,
  ];
  for (const [key, value] of Object.entries(ports)) {
    lines.push(`${key}=${value}`);
  }
  lines.push('');
  return lines.join('\n');
}

function branchExists(branch) {
  const result = spawnSync('git', ['rev-parse', '--verify', '--quiet', `refs/heads/${branch}`], {
    encoding: 'utf8',
  });
  return result.status === 0;
}

function repoRoot() {
  return gitOrThrow(['rev-parse', '--show-toplevel']).trim();
}

export function buildInstallCommands(worktreePath) {
  const cmds = [
    { label: 'root', args: ['install'], cwd: worktreePath },
  ];
  if (existsSync(join(worktreePath, 'server', 'package.json'))) {
    cmds.push({ label: 'server', args: ['install', '--prefix', 'server'], cwd: worktreePath });
  }
  return cmds;
}

function runInstalls(worktreePath) {
  const cmds = buildInstallCommands(worktreePath);
  for (const { label, args, cwd } of cmds) {
    process.stdout.write(`[wt-new] ${label} install: npm ${args.join(' ')} (in ${cwd})\n`);
    const result = spawnSync('npm', args, {
      cwd,
      stdio: 'inherit',
      shell: process.platform === 'win32',
    });
    if (result.error) {
      throw new Error(`npm ${label} install failed to spawn: ${result.error.message}`);
    }
    if (result.status !== 0) {
      throw new Error(`npm ${label} install exited ${result.status}`);
    }
  }
}

export function renderLaunchBlock({ worktreePath, branch, ports, slot, install }) {
  const winPath = worktreePath.replace(/\//g, '\\');
  const lines = [
    ``,
    `[wt-new] slot ${slot} → ports VITE=${ports.VITE_PORT} API=${ports.PORT} TTS=${ports.LOCAL_TTS_PORT} E2E=${ports.PLAYWRIGHT_PORT}`,
    `[wt-new] worktree created at ${worktreePath}`,
    `[wt-new] branch ${branch} (from ${branch === 'main' ? 'HEAD' : 'requested base'})`,
    ``,
    `Next steps — paste into a new terminal:`,
    ``,
    `  cd "${winPath}"`,
  ];
  if (install === false) {
    lines.push(`  npm install                  # root deps + husky hooks (skipped: --no-install)`);
    lines.push(`  npm install --prefix server  # server-side deps (skipped: --no-install)`);
  }
  lines.push(`  npm run dev        # frontend :${ports.VITE_PORT}, server :${ports.PORT}`);
  lines.push(`  # in another tab:`);
  lines.push(`  claude             # launch a parallel Claude Code session here`);
  lines.push(``);
  return lines.join('\n');
}

export async function main(argv) {
  let args;
  try {
    args = parseArgs(argv);
  } catch (err) {
    process.stderr.write(usage(err.message) + '\n');
    return 2;
  }
  if (args.help) {
    process.stdout.write(usage() + '\n');
    return 0;
  }
  if (!args.branch) {
    process.stderr.write(usage('missing branch name') + '\n');
    return 2;
  }

  const parsed = parseBranchName(args.branch);
  if (!parsed.ok) {
    process.stderr.write(usage(`invalid branch name "${args.branch}": ${parsed.reason}`) + '\n');
    return 2;
  }

  if (branchExists(args.branch)) {
    process.stderr.write(`Error: branch ${args.branch} already exists. Pick a different slug or delete it first.\n`);
    return 1;
  }

  const root = repoRoot();
  const worktreePath = resolve(root, '..', `wt-${parsed.slug}`);
  if (existsSync(worktreePath)) {
    process.stderr.write(`Error: ${worktreePath} already exists. Remove it (or choose a different slug) first.\n`);
    return 1;
  }

  // Existing worktrees include the main one, so count == slot for the new tree.
  const slot = countExistingWorktrees();
  const ports = computePorts(slot);

  process.stdout.write(`[wt-new] creating worktree at ${worktreePath} on new branch ${args.branch}\n`);
  gitOrThrow(['worktree', 'add', '-b', args.branch, worktreePath, args.from]);

  const envPath = join(worktreePath, '.env.local');
  writeFileSync(envPath, renderEnvLocal({ slot, branch: args.branch, ports }), 'utf8');
  process.stdout.write(`[wt-new] wrote ${envPath}\n`);

  if (args.install) {
    try {
      runInstalls(worktreePath);
    } catch (err) {
      process.stderr.write(`[wt-new] install step failed: ${err.message}\n`);
      process.stderr.write(`[wt-new] worktree at ${worktreePath} is created but deps are NOT installed.\n`);
      process.stderr.write(`[wt-new] resume manually: cd "${worktreePath}" && npm install && npm install --prefix server\n`);
      return 1;
    }
  } else {
    process.stdout.write(`[wt-new] --no-install: skipping npm install steps\n`);
  }

  process.stdout.write(
    renderLaunchBlock({ worktreePath, branch: args.branch, ports, slot, install: args.install }),
  );
  return 0;
}

// CLI entry — only runs when invoked directly, not when imported by tests.
const invokedAsCli =
  typeof process !== 'undefined' &&
  process.argv[1] &&
  process.argv[1].replace(/\\/g, '/').endsWith('scripts/wt-new.mjs');

if (invokedAsCli) {
  main(process.argv.slice(2)).then((code) => process.exit(code));
}
